# Generated by Django 4.0.1 on 2022-01-18 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=255)),
                ('roll', models.CharField(max_length=100)),
                ('vice_president', models.CharField(max_length=200)),
                ('general_secretary', models.CharField(max_length=200)),
                ('treasurer', models.CharField(max_length=200)),
                ('president', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.candidate')),
            ],
        ),
    ]
