# Generated by Django 4.0.1 on 2022-01-18 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('voters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='general_secretary',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='president',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.candidate'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='treasurer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vice_president',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
