# Generated by Django 4.0.1 on 2022-01-18 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('voters', '0002_alter_vote_general_secretary_alter_vote_president_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='president',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote_count', to='dashboard.candidate'),
        ),
    ]
