# Generated by Django 4.0.1 on 2022-01-18 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('voters', '0003_alter_vote_president'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='general_secretary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gen_sec_count', to='dashboard.candidate'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='treasurer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treasurer_count', to='dashboard.candidate'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vice_president',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vc_count', to='dashboard.candidate'),
        ),
    ]
